name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get version tag
        id: git_tag
        run: echo ::set-output name=VERSION::-${GITHUB_REF/refs\/tags\//}
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: jderusse/player
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Wait for package to be available
        timeout-minutes: 10
        run: |
          until $(curl --output /dev/null --silent --head --fail https://get.blackfire.io/blackfire-player${{ steps.git_tag.outputs.VERSION }}.phar); do
              printf '.'
              sleep 5
          done
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64
          build-args: |
            VERSION_SUFFIX=${{ steps.git_tag.outputs.VERSION }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
